export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'ADD_MESSAGE_FAILED';

export const FETCH_ALL_MESSAGES_START = 'FETCH_ALL_MESSAGES_START';
export const FETCH_ALL_MESSAGES_SUCCESS = 'FETCH_ALL_MESSAGES_SUCCESS';
export const FETCH_ALL_MESSAGES_FAILED = 'FETCH_ALL_MESSAGES_FAILED';